# Generated by Django 6.0 on 2026-01-12 10:04

import django.db.models.deletion
import django.utils.timezone
import offres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('niveau', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('missions', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('duree_mois', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('remuneration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lieu', models.CharField(max_length=150)),
                ('nb_postes', models.PositiveIntegerField(default=1)),
                ('remunere', models.BooleanField(default=False)),
                ('type_stage', models.CharField(blank=True, max_length=50)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PUBLIEE', 'Publiée'), ('ARCHIVEE', 'Archivée')], default='PUBLIEE', max_length=10)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='entreprises.entreprise')),
                ('filiere_cible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='offres.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointeOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('fichier', models.FileField(upload_to=offres.models.offre_piece_jointe_path)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='offres.offrestage')),
            ],
        ),
    ]
