# Generated by Django 6.0 on 2026-01-12 10:04

import conventions.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut_signature', models.CharField(choices=[('GENEREE', 'Générée'), ('EN_ATTENTE', 'En attente signature'), ('SIGNEE', 'Signée')], default='GENEREE', max_length=15)),
                ('document', models.FileField(upload_to=conventions.models.convention_upload_path)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='candidatures.candidature')),
            ],
        ),
    ]
