# Generated by Django 6.0 on 2026-01-12 10:04

import candidatures.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('EN_COURS', 'En cours'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('CONVENTION_SIGNEE', 'Convention signée')], default='RECUE', max_length=20)),
                ('cv', models.FileField(upload_to=candidatures.models.cv_upload_path)),
                ('lm', models.FileField(upload_to=candidatures.models.lm_upload_path)),
                ('message', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='offres.offrestage')),
            ],
            options={
                'unique_together': {('offre', 'etudiant')},
            },
        ),
    ]
